# Generated by Django 2.2.12 on 2020-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('service_type', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=8, null=True)),
                ('rating', models.CharField(max_length=2)),
            ],
        ),
    ]
