# Generated by Django 2.2.12 on 2020-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200907_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
